# NKjobs

# MySQL connection (required)
use-mysql: true
table-prefix: NKjobs_
host: localhost
port: 3306
dbName: minecraft
user: root
password:

# Options
server-name: 'world'
max-job: 1
ratio-from-spawner: 0.40
min-explore-money: 0.10
min-explore-exp: 0.10
global-blocks-timer: 5
max-registered-furnaces : 16
max-registered-brewingstands : 16